# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f78189542bc7d35b04546d3c336a8251fc28428ba1fe0c3ef70447059701a19900e0254e2672d320e28d4c3a8fa64c9a31501092da8304099b47396667de4e

test:
  secret_key_base: ae4c505fa6bc15c8b5c1f48de2584e5f4b96af2e75eec0bf9b52be2baf6ddd0ad40f8cb2489bf4a04298e18056088e7b3687fe19aa3476c5df9867067130803e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
